### PR TITLE
Rework networking of Notifico Bots

### LINKED ISSUE #112: Bots have issues on certain networks.
General catch-all ticket.

### PR DESCRIPTION
**Pull request by Dav1dde**
This "patch" usese the master branch of https://github.com/notifico/utopia (currently the deploy branch is used). So if you want to test it, install the master branch!

This is supposed to fix #112 (and all its "sub" issues), it implements basic CTCP answers (requested by someone on IRC, who didnt seem to open an issue on github ...).

This is a rather huge change, especially to the underlaying IRC library, please review! The more review, the faster it can be merged (and hopefully fix all the networking issues).

### CODE REVIEW

**Comment by BlackDragonGR** [comment]
i asked for the CTCP Plugin ! can we try it ?

**Comment by Dav1dde** [comment]
The CTCP Plugin is part of this pull request, once this version is deployed CTCP will work.

**Comment by BlackDragonGR** [comment]
Ok i will wait for it

**Comment by BlackDragonGR** [comment]
:o lets test it...!

**Comment by TkTech** [comment]
It is not yet live, it will be AB tested with a % of requests first.

**Comment by BlackDragonGR** [comment]
Damn... And i was thrilled about it... When will it be live ?

**Comment by TkTech** [comment]
Soon(TM)

I am currently changing jobs, so I have other priorities :)

**Comment by BlackDragonGR** [comment]
Looking forward to it...

**Comment by GLolol** [comment]
When is this going live? Notifico has been down for my network (`irc.overdrive.pw`) for days now.

The last quit message logged appears to be a netsplit:

```
 *** Quits: Not-9da9 (notifico@hidden-5af.sm4.199.198.IP) (millennium.overdrive.pw io.overdrive.pw)
```

**Comment by ThePsionic** [comment]
Yeah it has been over a month and a half now for me, was thinking about this yesterday but forgot to comment.

**Comment by DreadKnight** [comment]
Sigh, I hope this gets fixed soon. This bot is very unreliable atm.

**Comment by Dav1dde** [comment]
It is unfortunate that the PR isn't deployed yet, but sometimes real life is more important. 

If you really need a (reliable) working bot instance right now, hosting notifico on your own server might be worthwhile for the time beeing.

**Comment by TkTech** [comment]
Sorry, this was deployed a couple of weeks ago, but supervisor did not restart the bots properly. This has been corrected.

**Comment by DreadKnight** [comment]
Yeah, I can see it working now, nice :+1:

**Pull request merged**
